### ISSUE TITLE
Handling more codes

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/hetu#11]
In addition to validating and extracting information from Finnish personal identity codes, could there be a need for additional capabilities to analyze other kinds of codes? 

As an example the most recent version of hetu-package has a new function bid_ctrl that checks the validity of Finnish Business ID codes (y-tunnus / FO-nummer). Please note that unlike in Finnish personal identity codes, no similar information can be extracted from Finnish Business ID codes. Additional functions would most probably be similarly focused in their scope.

Teppo Vuori's website (in Finnish) has a nice list of different codes and their calculation methods respectively that may bring some ideas: http://tarkistusmerkit.teppovuori.fi/tarkmerk.htm

**Comment by antagomir** [comment]
In my view it would be quite useful to have at least validators (and information extractors?) for some of the most common ID types; such as Y-tunnus (company ID), IBAN etc. Teppo Vuori's website has a good compilation. 

Technically it would be easy to host these in the same package; not sure if a separate package would be necessary. JUst that the pkg name "hetu" would then slightly limited w.r.t. overall content. Not sure if that really is a problem as long as the tools work well and can be found.

**Comment by pitkant** [comment]
I think the current scope is good enough for the purpose of this package: "Write programs that do one thing and do it well." 

Even the added functionality of generation and validation of Business ID codes is bit outside of the scope but exceptions just prove the rule. A bonus feature. :)
