### ISSUE TITLE
HackMD

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/hetu#4]
Experiment with [HackMD](https://opensource.com/article/19/7/enable-collaboration-hackmd) collaborative markdown editing and [add a badge](https://hackmd.io/c/tutorials/%2Fs%2Flink-with-github#Add-GitHub-badge) to package homepage if relevant.

**Comment by jukop** [comment]
I made an account at least. I need to try this more some other time.

**Comment by pitkant** [comment]
I'm not sure if this is relevant at this stage. I'll make a note to self to keep this in mind for future projects.
