### ISSUE TITLE
Function name: pin_to_date (Get birth date)

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/hetu#5]
I am wondering if we should name this function just as "pin_date"? Would be more clear imo.

**Comment by MansMeg** [comment]
I agree. We could start by deprecating pin_to_date() for now and point to pin_date(). If you like you can do that in a PR. Otherwise I can fix it later on.

**Comment by antagomir** [comment]
Sure, PR will come. Same change to be done in "hetu" pkg then.
